ALTER PROCEDURE [dbo].[SP_KTTrungDDH]
@MADDH NVARCHAR(15)
AS
BEGIN
		IF EXISTS(SELECT * FROM dbo.DatHang AS DH WHERE DH.MasoDDH = @MADDH)
			RETURN 1;
		IF EXISTS(SELECT * FROM LINK1.QLVT.dbo.DatHang AS DH WHERE DH.MasoDDH = @MADDH)
			RETURN 1; 
	RETURN 0;
END