ALTER PROCEDURE [dbo].[SP_KTTrungPX]
@MAPX NVARCHAR(15)
AS
BEGIN
		IF EXISTS(SELECT * FROM dbo.PhieuXuat AS PX WHERE PX.MAPX = @MAPX)
			RETURN 1;
		IF EXISTS(SELECT * FROM LINK1.QLVT.dbo.PhieuXuat AS PX WHERE PX.MAPX = @MAPX)
			RETURN 1; 
	RETURN 0;
END
