CREATE PROC [dbo].[SP_KIEMTRASOLUONGVATTU]
@MAPHIEU NCHAR(8),
@MAVT NCHAR(4),
@SOLUONG INT
AS
BEGIN
IF(@SOLUONG<=(SELECT SOLUONG FROM CTDDH WHERE MasoDDH = @MAPHIEU AND MAVT = @MAVT))
		SELECT SOLUONG FROM CTDDH WHERE MasoDDH = @MAPHIEU AND MAVT = @MAVT
ELSE
	RAISERROR(N'SỐ LƯỢNG VẬT TƯ KHÔNG HỢP LỆ !',16,1)
END
