USE [QLVT]
GO
/****** Object:  StoredProcedure [dbo].[SP_RP_CTSLTGHN]    Script Date: 23/11/2021 15:39:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_RP_CTSLTGHN] 
@date1 date, @date2 date,@group nvarchar(10)
AS
IF(@group!='CONGTY')
	BEGIN
		SELECT MONTHYEAR,TENVT,TONGSL, TONGGT FROM
(select MONTHYEAR,MAVT,SUM(SOLUONG) as TONGSL,SUM(TONGGT) AS TONGGT
FROM  
(select CONCAT(MONTH(NGAY),'/',YEAR(NGAY)) as MONTHYEAR,MAPN from PhieuNhap where NGAY BETWEEN @date1 and @date2) R1,
(select MAVT,MAPN,SOLUONG,DONGIA*SOLUONG as TONGGT from CTPN) R2
WHERE R1.MAPN=R2.MAPN
GROUP BY MONTHYEAR,MAVT ) R3
left join
(select TENVT,MAVT from Vattu) R4
on (R3.MAVT=R4.MAVT)
ORDER BY MONTHYEAR DESC
	END
ELSE
	BEGIN
		SELECT MONTHYEAR,TENVT,TONGSL, TONGGT FROM
(select MONTHYEAR,MAVT,SUM(SOLUONG) as TONGSL,SUM(TONGGT) AS TONGGT
FROM  
(select CONCAT(MONTH(NGAY),'/',YEAR(NGAY)) as MONTHYEAR,MAPN from PhieuNhap where NGAY BETWEEN @date1 and @date2) R1,
(select MAVT,MAPN,SOLUONG,DONGIA*SOLUONG as TONGGT from CTPN) R2
WHERE R1.MAPN=R2.MAPN
GROUP BY MONTHYEAR,MAVT) R3
left join
(select TENVT,MAVT from Vattu) R4
on (R3.MAVT=R4.MAVT)
UNION
SELECT MONTHYEAR,TENVT,TONGSL, TONGGT FROM
(select MONTHYEAR,MAVT,SUM(SOLUONG) as TONGSL,SUM(TONGGT) AS TONGGT
FROM  
(select CONCAT(MONTH(NGAY),'/',YEAR(NGAY)) as MONTHYEAR,MAPN from LINK1.QLVT.dbo.PhieuNhap where NGAY BETWEEN @date1 and @date2) R1,
(select MAVT,MAPN,SOLUONG,DONGIA*SOLUONG as TONGGT from LINK1.QLVT.dbo.CTPN) R2
WHERE R1.MAPN=R2.MAPN
GROUP BY MONTHYEAR,MAVT) R3
left join
(select TENVT,MAVT from Vattu) R4
on (R3.MAVT=R4.MAVT)
ORDER BY MONTHYEAR DESC

	END
