CREATE proc [dbo].[SP_TIMPHIEUNHAP]
@MAPN NCHAR(8)
AS
BEGIN
	IF EXISTS (SELECT MAPN FROM DBO.PHIEUNHAP WHERE MAPN = @MAPN)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT MAPN FROM LINK1.QLVT_DATHANG.DBO.PHIEUNHAP WHERE MAPN = @MAPN)
			RETURN 1;
		ELSE
			RAISERROR(N'PHIẾU NHẬP BẠN TÌM KHÔNG TỒN TẠI',16,1)
END
