CREATE PROC [dbo].[SP_TIMCTDDH]
@MADDH NCHAR(8),
@MAVT NCHAR(4)
AS
BEGIN
	IF EXISTS (SELECT * FROM DBO.CTDDH WHERE MASODDH = @MADDH AND MAVT = @MAVT)
		RETURN 1;
	ELSE
		IF EXISTS (SELECT * FROM LINK1.QLVT_DATHANG.DBO.CTDDH WHERE MASODDH = @MADDH AND MAVT = @MAVT)
			RETURN 1;
		ELSE
			RAISERROR(N'CHI TIẾT ĐƠN ĐẶT HÀNG BẠN TÌM KHÔNG TỒN TẠI',16,1)
END
